package com.example.mybatis.model;

import java.util.Date;

public class TcMsgCodeConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.msg_code
     *
     * @mbg.generated
     */
    private String msgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.default_msg
     *
     * @mbg.generated
     */
    private String defaultMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.res_code
     *
     * @mbg.generated
     */
    private String resCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_msg_code_config.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.ID
     *
     * @return the value of tc_msg_code_config.ID
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.ID
     *
     * @param id the value for tc_msg_code_config.ID
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.msg_code
     *
     * @return the value of tc_msg_code_config.msg_code
     * @mbg.generated
     */
    public String getMsgCode() {
        return msgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.msg_code
     *
     * @param msgCode the value for tc_msg_code_config.msg_code
     * @mbg.generated
     */
    public void setMsgCode(String msgCode) {
        this.msgCode = msgCode == null ? null : msgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.default_msg
     *
     * @return the value of tc_msg_code_config.default_msg
     * @mbg.generated
     */
    public String getDefaultMsg() {
        return defaultMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.default_msg
     *
     * @param defaultMsg the value for tc_msg_code_config.default_msg
     * @mbg.generated
     */
    public void setDefaultMsg(String defaultMsg) {
        this.defaultMsg = defaultMsg == null ? null : defaultMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.params
     *
     * @return the value of tc_msg_code_config.params
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.params
     *
     * @param params the value for tc_msg_code_config.params
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.res_code
     *
     * @return the value of tc_msg_code_config.res_code
     * @mbg.generated
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.res_code
     *
     * @param resCode the value for tc_msg_code_config.res_code
     * @mbg.generated
     */
    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.remark
     *
     * @return the value of tc_msg_code_config.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.remark
     *
     * @param remark the value for tc_msg_code_config.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.create_time
     *
     * @return the value of tc_msg_code_config.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.create_time
     *
     * @param createTime the value for tc_msg_code_config.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_msg_code_config.update_time
     *
     * @return the value of tc_msg_code_config.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_msg_code_config.update_time
     *
     * @param updateTime the value for tc_msg_code_config.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}