package com.example.mybatis.model;

import java.util.Date;

public class TmpUserPayAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_user_pay_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_user_pay_account.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_user_pay_account.trade_no
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_user_pay_account.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_user_pay_account.pay_method
     *
     * @mbg.generated
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_user_pay_account.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_user_pay_account.id
     *
     * @return the value of tmp_user_pay_account.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_user_pay_account.id
     *
     * @param id the value for tmp_user_pay_account.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_user_pay_account.member_id
     *
     * @return the value of tmp_user_pay_account.member_id
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_user_pay_account.member_id
     *
     * @param memberId the value for tmp_user_pay_account.member_id
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_user_pay_account.trade_no
     *
     * @return the value of tmp_user_pay_account.trade_no
     * @mbg.generated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_user_pay_account.trade_no
     *
     * @param tradeNo the value for tmp_user_pay_account.trade_no
     * @mbg.generated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_user_pay_account.account
     *
     * @return the value of tmp_user_pay_account.account
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_user_pay_account.account
     *
     * @param account the value for tmp_user_pay_account.account
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_user_pay_account.pay_method
     *
     * @return the value of tmp_user_pay_account.pay_method
     * @mbg.generated
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_user_pay_account.pay_method
     *
     * @param payMethod the value for tmp_user_pay_account.pay_method
     * @mbg.generated
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_user_pay_account.create_time
     *
     * @return the value of tmp_user_pay_account.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_user_pay_account.create_time
     *
     * @param createTime the value for tmp_user_pay_account.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}