package com.example.mybatis.dao;

import com.example.mybatis.model.TcMsgCodeConfig;

import java.util.List;

public interface TcMsgCodeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_msg_code_config
     *
     * @mbg.generated
     */
    int insert(TcMsgCodeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_msg_code_config
     *
     * @mbg.generated
     */
    List<TcMsgCodeConfig> selectAll();
}